### ISSUE TITLE
Some question about the data used in the data

### ISSUE THREAD

**Issue by ChiShengChen** [eeyhsong/NICE-EEG#1]
Thank you for good work! I have some question about reproducing the work,
Dose the preprocessed eeg data `./Data/Things-EEG2/Preprocessed_data_250Hz/` is the `[Preprocessed EEG data](https://osf.io/anp5v/)` on the  paper `[A large and rich EEG dataset for modeling human visual object recognition](https://www.sciencedirect.com/science/article/pii/S1053811922008758?via%3Dihub)` 's OSF web: https://osf.io/3jk45/ ?

or you directly processing the data get from the web "Source EEG Data" or "Raw EEG Data"?

**Comment by eeyhsong** [comment]
Hi, @ChiShengChen 
I got the raw data and preprocessed it with some changes compared to the [Preprocessed EEG data]. You could refer to the preprocessing part of our code.

**Comment by ChiShengChen** [comment]
> Hi, @ChiShengChen I got the raw data and preprocessed it with some changes compared to the [Preprocessed EEG data]. You could refer to the preprocessing part of our code.

Thanks for quick reply! It works well!
