### ISSUE TITLE
About center_xxx.npy (used in training) do not generate from center_fea_xxx.py

### ISSUE THREAD

**Issue by ChiShengChen** [eeyhsong/NICE-EEG#2]
I met the problem as below when I finished all the steps till `python nice_stand.py` to train:
`(nice_eeg) mw@mw-System-Product-Name:~/my_data_disk_5T/eeg-image/THINGS-EEG/NICE-EEG$ python nice_stand.py 
Tue Mar  5 00:46:03 2024
seed is 1933
Subject 1
initial define done.
Traceback (most recent call last):
  File "nice_stand.py", line 449, in <module>
    main()
  File "nice_stand.py", line 427, in main
    Acc, Acc3, Acc5 = ie.train()
  File "nice_stand.py", line 233, in train
    test_center = np.load(self.test_center_path + 'center_' + self.args.dnn + '.npy', allow_pickle=True)
  File "/home/meow/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/mw/my_data_disk_5T/eeg-image/THINGS-EEG/NICE-EEG/Data/Things-EEG2/Image_set/center_clip.npy'
`

Take `center_fea_clip.py` for instance, the code only has
`np.save(os.path.join(args.project_dir, 'center_all_image_clip.npy'), all_centers)` means only generate the `'center_all_image_clip.npy'`, 
how can I get the `center_xxx.npy `(used in training) ?

**Comment by eeyhsong** [comment]
You may average the center of each concept to get the center_xxx.npy.
I have uploaded a version for reference here https://github.com/eeyhsong/NICE-EEG/blob/main/center_clip.npy.
🤝🤝

**Comment by ChiShengChen** [comment]
It works well!
Thank you very much for your attention and patience!

**Comment by ChiShengChen** [comment]
Please let me ask one more question about the center_clip.npy you have provided, is this file contain all the subjects? I only try the sub_10 for try-run, the accuracy is better than the result in your paper:
![2024-03-11 16-54-09 的螢幕擷圖](https://github.com/eeyhsong/NICE-EEG/assets/22126443/2e94face-c709-4e06-9112-2e3bdf6002d4)

Thanks again for your support!
