### ISSUE TITLE
Hello, I would like to ask where the visualization script for this project is located, thank you.

### ISSUE THREAD

**Issue by 2050271010** [eeyhsong/NICE-EEG#7]
I saw in the readme that you marked the location of the visualization script as ./visualization/, but I did not find this path or file. I look forward to your reply, thank you.

**Comment by eeyhsong** [comment]
Hello @2050271010, you may refer to /draw_pic for some information.

**Comment by 2050271010** [comment]
Okay, I understand what you mean, thank you for your explanation.
